### PR TITLE
Rails 5 updates to LettersController

### PR DESCRIPTION
**Pull request by mikeycgto**

### CODE REVIEW

**Comment by thomasdziedzic** [comment]
Would we want to keep before_filter for older versions?

**Comment by harigopal** [comment]
@fgrehm Could this be merged, please?

**Comment by maurosbu** [comment]
@fgrehm Waiting for a new release, thx.

**Comment by fgrehm** [comment]
Sorry but I no longer use this gem, anyone up for taking it over? 🍺

**Comment by pseudomuto** [comment]
Hey @fgrehm, I'd be willing to take this over. Still looking?

**Comment by pseudomuto** [comment]
ping @fgrehm

**Comment by fgrehm** [comment]
@pseudomuto invited! once you have a release ready to go LMK and I'll give you the permissions on rubygems to push there as well. 🍻

**Comment by pseudomuto** [comment]
Thanks for the PR @mikeycgto!

**Comment by mikeycgto** [comment]
happy to help! ❤️

**Comment by pseudomuto** [comment]
For anyone waiting on this, version 1.3.1 was just released and includes this change

**Pull request merged**
