### PR TITLE
Add require_dependency

### PR DESCRIPTION
**Pull request by koheisg**
@davekaro @pseudomuto 
thank you for your feedbacks on https://github.com/fgrehm/letter_opener_web/pull/79

### CODE REVIEW

**Comment by pseudomuto** [comment]
@koheisg this looks good, but can you change those double quotes to single quotes? I know it seems silly, but I once made a giant commit to fix all the rubocop errors and never want to do it again 😄 

You can run `bundle exec rubocop` after to make sure it's not going to fail in CI again.

**Comment by koheisg** [comment]
@pseudomuto thank you for your support. I checked CI is green.

**Comment by pseudomuto** [comment]
Thanks for doing this @koheisg!

Fixes #76

**Comment by jnraine** [comment]
@pseudomuto we're hitting this as well. Glad to see it is fixed! Would you be able to cut a release of the gem that includes this?

**Comment by pseudomuto** [comment]
@jnraine version 1.3.4 has been released

**Comment by rafaelsales** [comment]
@fgrehm Can you make a release so that we can use this fix? Thanks

**Comment by pseudomuto** [comment]
@rafaelsales v1.3.4 has been released with this patch. Are you having issues with the require dependency?

**Pull request merged**
