### PR TITLE
Made compatible with Rails 3

### PR DESCRIPTION
**Pull request by gbonline**

### CODE REVIEW

**Comment by pseudomuto** [comment]
Hey @gbonline, sorry for the _very_ late response. In the future please `@` me in the PR description so I get notified.

At this point, Rails 3 (even 4) is very old and not something I'd want to take on. Is this still an issue for you?

**Comment by gbonline** [comment]
Hi, Pseudomuto
maybe do you speak italian?  your name sound italiano...
I've used this gem on a old project, the client of the project wanted to update, so I took everything back in hand and installed the new gems. This one didn't work anymore on the project, so I customized it for the rails 3 version, then I proposed to update it with a little modify to make it compatible with the old rails.
Answering your question "Is still an issue for you?", No anymore.
best regards

**Comment by fgrehm** [comment]
> @pseudomuto At this point, Rails 3 (even 4) is very old and not something I'd want to take on.

Me neither :sweat_smile: 

> @gbonline Answering your question "Is still an issue for you?", No anymore.

Awesome, I guess we can close this, @pseudomuto when me or you have the time, lets bump the deps on the gemspec

https://github.com/fgrehm/letter_opener_web/blob/968d1a0c3ff679fdfabdd2b449b6573e992b4c64/letter_opener_web.gemspec#L23-L25

I'll create a ticket for that so we don't forget

**Comment by fgrehm** [comment]
@gbonline forgot to say: thank you for your contributions and sorry we took so long to get back to you!

**Pull request closed without merging**
